name: Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: echo "build main"
  call-workflow:
    uses: ./.github/workflows/reusable.yaml
